### PR TITLE
Update transmission-3.00.tar.xz to 4.0.1

### PR DESCRIPTION
**Pull request by Amanse**

### CODE REVIEW

**Comment by bbhtt** [comment]
> Build [25089 failed](https://buildbot.flathub.org/#/builders/6/builds/25089)

Try with the following versions:

mm-common 1.0.5 : https://download.gnome.org/sources/mm-common/1.0/mm-common-1.0.5.tar.xz
libsigcc++ 3.4.0 : https://download.gnome.org/sources/libsigc%2B%2B/3.4/libsigc%2B%2B-3.4.0.tar.xz
glibmm 2.74.0: https://download.gnome.org/sources/glibmm/2.74/glibmm-2.74.0.tar.xz
cairomm 1.16.2 : https://www.cairographics.org/releases/cairomm-1.16.2.tar.xz
pangomm 2.50.1 : https://download.gnome.org/sources/pangomm/2.50/pangomm-2.50.1.tar.xz
gtkmm 4.8.0 : https://download.gnome.org/sources/gtkmm/4.8/gtkmm-4.8.0.tar.xz

If this doesn't work might need to downgrade runtime to 42 (depending on build failures)

**Comment by wjt** [comment]
We can try lifting https://github.com/flathub/de._0x539.gobby/blob/master/gtkmm.json, which I copy-paste between about 5 different apps at this point…

**Comment by wjt** [comment]
OK, interesting, it really has both GTK 3 and GTK 4 support.

**Comment by bbhtt** [comment]
> We can try lifting https://github.com/flathub/de._0x539.gobby/blob/master/gtkmm.json, which I copy-paste between about 5 different apps at this point…

Transmission 4.0 has GTK4 support it links against newer gtkmm https://github.com/transmission/transmission/blob/1f1e614f9975399f5c5e847c76f4f61104649726/CMakeLists.txt#L287

**Comment by Amanse** [comment]
> Also downgrade the runtime to 42, see #46
i did that locally, still same error with glibmm
> Try with the following versions:
thanks! I'll try with these

is there some rule about compiling packages because transmission is giving latest binaries in their repo now

**Comment by wjt** [comment]
I'm not sure it's written down but it is, at least, strongly preferred for apps to be built on Flathub.

**Comment by tinywrkb** [comment]
This PR is mixing stable and unstable package releases. Read the documentation for each package.  
If you don't want to bother doing that, then the principle is that odd releases are unstable. Though I think there's a minimal glib version matching for packages of the gtkmm project, and glib comes from the runtime. 

Don't use binary releases, it's a bad idea. You'll miss important Flatpak related changes, like the Fontconfig patches, and application developers are usually too lazy to properly build and package features that they don't care about, e.g. IM modules (see the Calibre's monstrosity binary release).

**Comment by bbhtt** [comment]
I picked and squashed all your commits and added the changes on top in https://github.com/flathub/com.transmissionbt.Transmission/pull/55

**Pull request closed without merging**
